"""
	spatial_crop(img, roi_start, roi_end)

General purpose cropper to produce sub-volume region of interest (ROI).
The start and end coordinates of the ROI must be provided.
"""
function spatial_crop(img, roi_start, roi_end)
	return img[roi_start[1]:roi_end[1], roi_start[2]:roi_end[2]]
end

"""
	crop_foreground(img, select_function)

Crop an image using a bounding box. The bounding box is generated by selecting foreground using select_function
at channels channel_indices (if provided). Margin can added in each spatial dimension of the bounding box.
The typical usage is to help training and evaluation if the valid part is small in the whole medical image.
Users can define arbitrary function to select expected foreground from the whole image or specified channels.
And it can also add margin to every dimension of the bounding box of foreground object.
"""
function crop_foreground(img, select_function)
	box_start, box_end = generate_spatial_bounding_box(img, select_function)
	cropped = spatial_crop(img, box_start, box_end)
	return cropped
end

function crop_foreground(img, select_function, channel_indices)
	box_start, box_end = generate_spatial_bounding_box(img, select_function, channel_indices)
	cropped = spatial_crop(img, box_start, box_end)
	return cropped
end